export const FETHC_QUIZES_START = 'FETHC_QUIZES_START'
export const FETHC_QUIZES_SUCCESS = 'FETHC_QUIZES_SUCCESS'
export const FETHC_QUIZES_ERROR = 'FETHC_QUIZES_ERROR'
export const FETHC_QUIZ_SUCCESS = 'FETHC_QUIZ_SUCCESS'

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
